<?php
/**
 * Created by PhpStorm.
 * User: thtmo
 * Date: 18/03/2019
 * Time: 19:35
 */

namespace thtmorais\pace;

use yii\web\AssetBundle;

class PaceAsset extends AssetBundle
{
    public $sourcePath = "@npm";

    private $path = "pace-js/";

    public $jsOptions = ['position' => \yii\web\View::POS_HEAD];

    public function registerAssetFiles($view)
    {
        if(YII_DEBUG){
            $this->js = [$this->path.'pace.js'];
        }else{
            $this->js = [$this->path.'pace.min.js'];
        }

        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}