<?php
/**
 * Created by PhpStorm.
 * User: thtmo
 * Date: 18/03/2019
 * Time: 19:35
 */

namespace thtmorais\pace;

use yii\web\AssetBundle;

class PaceAsset extends AssetBundle
{
    public $sourcePath = "@npm";

    public function registerAssetFiles($view)
    {
        $this->js = YII_DEBUG?'pace-js/pace.js':'pace-js/pace.min.js';
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}