<?php
/**
 * Created by PhpStorm.
 * User: thtmo
 * Date: 18/03/2019
 * Time: 19:35
 */

namespace thtmorais\pace;

use Yii;
use yii\base\Widget;

/**
 * Class Pace
 * @package thtmorais\pace
 */
class Pace extends Widget
{
    public $color;
    public $theme;
    public $options;

    /**
     *
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string|void
     * @throws \yii\base\InvalidConfigException
     */
    public function run()
    {
        if(isset(Yii::$app->params['paceOptions']['color']) && !empty(Yii::$app->params['paceOptions']['color']) && $this->color === null) {
            $this->color = Yii::$app->params['paceOptions']['color'];
        }elseif ($this->color === null){
            $this->color = 'blue';
        }

        if(isset(Yii::$app->params['paceOptions']['theme']) && !empty(Yii::$app->params['paceOptions']['theme']) && $this->theme === null) {
            $this->theme = Yii::$app->params['paceOptions']['theme'];
        }elseif ($this->theme === null){
            $this->theme = 'minimal';
        }

        if(isset(Yii::$app->params['paceOptions']['options']) && !empty(Yii::$app->params['paceOptions']['options']) && $this->options === null) {
            $this->getView()->registerJs('window.paceOptions=' . json_encode(Yii::$app->params['paceOptions']['options']), \yii\web\View::POS_BEGIN);
        }

        PaceAsset::register($this->getView());
        $asset = Yii::$app->assetManager->publish("@npm/pace-js",['forceCopy'=>YII_DEBUG]);

        $this->getView()->registerCssFile($asset[1].'/themes/'.$this->color.'/pace-theme-'.$this->theme.'.css');
    }
}