<?php

namespace thtmorais\pace;

use yii\web\AssetBundle;

/**
 * Class PaceAsset
 * @package thtmorais\pace
 */
class PaceAsset extends AssetBundle
{
    /**
     * @var string
     */
    public $sourcePath = "@npm";

    /**
     * @var string
     */
    private $path = "pace-js/";

    /**
     * @var array
     */
    public $jsOptions = ['position' => \yii\web\View::POS_HEAD];

    /**
     * @param \yii\web\View $view
     */
    public function registerAssetFiles($view)
    {
        $this->js = [$this->path . YII_DEBUG ? 'pace.js' : 'pace.min.js'];

        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}